include:
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/PreCommit.gitlab-ci.yml"
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/ArtifactoryPyPI.gitlab-ci.yml"
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/SonarScanner.gitlab-ci.yml"

variables:
  CC: "mpicc"
  CXX: "mpic++"

run-tests:
  tags:
    - docker
  stage: test
  image: continuumio/miniconda3:24.7.1-0
  before_script:
    - conda env create -y -n po3 --file environment.yml
    - conda init bash
    - source ~/.bashrc
    - conda activate po3
    - conda install -y -c conda-forge gcc gxx mpich mpich-mpicc mpich-mpicxx pytest pytest-cov coverage numpy scipy matplotlib
    - pip install .
  script:
    - pytest tests --junitxml=junit.xml --cov-report xml --cov-report term --cov orbit
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - junit.xml
      - coverage.xml
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build-pypi-package-py310:
  extends: build-pypi-package
  image: continuumio/miniconda3:24.7.1-0
  before_script:
    - conda update -y -n base -c defaults conda
    - conda env create -y -n python310 --file environment.yml
    - conda init bash
    - source ~/.bashrc
    - conda activate python310
    - conda install -y -c conda-forge python=3.10 build gcc gxx git mpich mpich-mpicc mpich-mpicxx

build-pypi-package:
  image: continuumio/miniconda3:24.7.1-0
  script:
    - git config --global --add safe.directory /builds/ess-crs/pyorbit3
    - python -m build
  before_script:
    - conda update -y -n base -c defaults conda
    - conda env create -y -n python311 --file environment.yml
    - conda init bash
    - source ~/.bashrc
    - conda activate python311
    - conda install -y -c conda-forge python=3.11 build gcc gxx git git-lfs mpich mpich-mpicc mpich-mpicxx
